language: java
jdk:
 - oraclejdk8
sudo: required
services:
  - mysql
before_install:
  - mysql -u root -e "CREATE DATABASE blackmarket;"
test:
  adapter: mysql2
  database: blackmarket
  username: root
  encoding: utf8
install:
- cp ./src/test/resources/application.yml.example ./src/test/resources/application.yml
- mvn -N io.takari:maven:wrapper
- ./mvnw clean test
- bash <(curl -s https://codecov.io/bash)
