language: java
jdk:
 - oraclejdk8
install:
- cp ./src/main/resources/application.yml.example ./src/main/resources/application.yml
- mvn -N io.takari:maven:wrapper
- ./mvnw clean install
- bash <(curl -s https://codecov.io/bash)
